name: publish
on: [push]
jobs:
       build:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - name: Login to GitHub Container Registry
                       uses: docker/login-action@v1
                       with:
                        registry: ghcr.io
                        username: ${{ github.actor }}
                        password: ${{ secrets.GITHUB_TOKEN }}
                     - name: Build and push
                       env:
                        DATABASE_URL: ${{ env.DATABASE_URL }}
                       run: |
                            docker build . --tag ghcr.io/tautf/foinix:latest
                            docker run ghcr.io/tautf/foinix:latest
                            docker push ghcr.io/tautf/foinix:latest